spring:
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
  application:
    name: job-li-ips
  datasource: # my local config, change for testing
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    jdbcUrl: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: myuser
    password: mypassword
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  cloud:
    task:
      table-prefix: TASK_
    config:
      enabled: false

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
